# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  install:chezmoi:
    desc: "Install chezmoi via script"
    cmd: ./scripts/chezmoi.sh

  install:nvim:
    desc: "Install neovim from source via script"
    vars:
      VERSION: '{{.VERSION | default "stable"}}'
      INSTALL_PREFIX: '{{.INSTALL_PREFIX | default "/usr/local"}}'
    cmd: ./scripts/nvim.sh {{.INSTALL_PREFIX}} {{.VERSION}}

  install:prek:
    desc: "Install prek via script for handling pre-commit hooks"
    cmd: ./scripts/prek.sh

  install:alacritty:
    desc: "Install alacritty via script"
    cmd: ./scripts/alacritty.sh

  install:fonts:
    desc: "Install configured fonts (list in README.md)"
    cmd: ./scripts/fonts.sh

  install:nvim-deps:
    desc: "Install Neovim runtime dependencies"
    cmd: ./scripts/nvim-deps.sh

  install:zellij:
    desc: "Install zellij via script"
    cmd: ./scripts/install-zellij.sh

  install:all:
    desc: "Install all the dependencies via scripts"
    vars:
      VERSION: '{{.VERSION | default "stable"}}'
      INSTALL_PREFIX: '{{.INSTALL_PREFIX | default "/usr/local"}}'
    cmds:
      - task: install:alacritty
      - task: install:chezmoi
      - task: install:prek
      - task: install:nvim
        vars:
          { VERSION: "{{.VERSION }}", INSTALL_PREFIX: "{{ .INSTALL_PREFIX }}" }
      - task: install:fonts

  uninstall:alacritty:
    desc: "Uninstall alacritty"
    cmd: ./scripts/alacritty.sh --uninstall

  uninstall:task:
    desc: "Uninstall task"
    cmd: ./scripts/task.sh --uninstall

  uninstall:chezmoi:
    desc: "Uninstall chezmoi"
    cmd: ./scripts/chezmoi.sh --uninstall

  uninstall:prek:
    desc: "Uninstall prek"
    cmd: ./scripts/prek.sh --uninstall

  uninstall:zellij:
    desc: "Uninstalls Zellij"
    cmd: ./scripts/install-zellij.sh uninstall

  _chezmoi:
    internal: true
    cmd: chezmoi {{.CLI_ARGS}} --source="{{.ROOT_DIR}}"

  init:
    desc: "Initialize chezmoi for the first time or re-initialize (use with caution!)"
    cmds:
      - task: _chezmoi
        vars: { CLI_ARGS: "init" }

  apply:
    desc: "Apply dotfiles using chezmoi"
    cmds:
      - task: _chezmoi
        vars: { CLI_ARGS: "apply" }

  diff:
    desc: "Diff dotfiles using chezmoi"
    cmds:
      - task: _chezmoi
        vars: { CLI_ARGS: "diff" }

  add:
    desc: "Import a file or directory into source"
    requires:
      vars:
        - TARGET
    cmds:
      - task: _chezmoi
        vars:
          CLI_ARGS: "add {{.TARGET}}"

  docker:nvim:build:
    desc: "Build the Neovim Docker image"
    cmds:
      - docker build -t nvim-env -f nvim-docker/Dockerfile .

  docker:nvim:run:
    desc: "Run the Neovim Docker container"
    cmds:
      - docker run -it --rm -v {{.USER_WORKING_DIR}}:/root/workspace nvim-env {{.CLI_ARGS}}

  docker:nvim:shell:
    desc: "Run a shell inside the Neovim Docker container for debugging/exploration"
    cmds:
      - docker run -it --rm -v {{.USER_WORKING_DIR}} nvim-env /bin/bash
