# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  install:chezmoi:
    desc: "Install chezmoi via script"
    cmd: ./scripts/install-chezmoi.sh

  install:nvim:
    desc: "Install neovim from source via script"
    cmd: ./scripts/install-neovim-from-source.sh

  install:prek:
    desc: "Install prek via script for handling pre-commit hooks"
    cmd: ./scripts/install-prek.sh

  install:alacritty:
    desc: "Install alacritty via script"
    cmd: ./scripts/install-alacritty.sh

  install:all:
    desc: "Install all the dependencies via scripts"
    deps:
      - install:chezmoi
      - install:prek
      - install:nvim

  _chezmoi:
    internal: true
    cmd: chezmoi {{.CLI_ARGS}} --source="{{.ROOT_DIR}}"

  init:
    desc: "Initialize chezmoi for the first time or re-initialize (use with caution!)"
    cmds:
      - task: _chezmoi
        vars: { CLI_ARGS: "init" }

  apply:
    desc: "Apply dotfiles using chezmoi"
    cmds:
      - task: _chezmoi
        vars: { CLI_ARGS: "apply" }

  diff:
    desc: "Diff dotfiles using chezmoi"
    cmds:
      - task: _chezmoi
        vars: { CLI_ARGS: "diff" }

  docker:nvim:build:
    desc: "Build the Neovim Docker image"
    cmds:
      - docker build -t nvim-env -f nvim-docker/Dockerfile .

  docker:nvim:run:
    desc: "Run the Neovim Docker container"
    cmds:
      - docker run -it --rm -v {{.USER_WORKING_DIR}}:/root/workspace nvim-env {{.CLI_ARGS}}

  docker:nvim:shell:
    desc: "Run a shell inside the Neovim Docker container for debugging/exploration"
    cmds:
      - docker run -it --rm -v {{.USER_WORKING_DIR}} nvim-env /bin/bash
